### PR TITLE
column: fix, doc

### PR DESCRIPTION
**Pull request by steakknife**
Regenerated `lib/oedipus_lex.rex.rb` using `rake bootstrap`.

### CODE REVIEW

**Comment by zenspider** [comment]
Never _ever_ use `git add -a`. Please try again, clean up the PR, and `git push -f`.

**Comment by steakknife** [comment]
Relax, be nice and don't lecture, chief.  I usually do `git commit -Sam` and I know how to squash commits.

**Comment by zenspider** [comment]
I am relaxed, I was nice, and I didn't lecture... But if you want to take your ball and go home, that's fine too.

Another suggestion: either 2 PRs or at least 2 commits if you are addressing 2 issues (docs & bootstrap)

**Comment by zenspider** [comment]
Just to follow up: I've manually merged your doco and column fix and credited you for it. Thank you for your contribution.

**Pull request closed without merging**
